name: CI/CD
on:
  push:
    branches:
      - master
  
jobs:
  deploy-laravel-vps:
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ratu_report
          MYSQL_USER: ratu
          MYSQL_PASSWORD: Ratu123!@#
          MYSQL_ROOT_PASSWORD: Ratu123!@#
          MYSQL_ROOT_HOST: '%'
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_mysql, zip, bcmath
        coverage: none

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Set Directory Permissions (Pre-Key Generate)
      run: |
        sudo chmod 777 .env
        sudo chmod -R 775 storage bootstrap/cache
        sudo chown -R www-data:www-data storage bootstrap/cache

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Check .env Existence
      run: ls -lah .env && cat .env | grep APP_KEY || echo ".env is missing!"

    - name: Wait for MySQL to be Ready
      run: |
        while ! mysqladmin ping -h"103.127.97.47" -P"3306" -u"ratu" -p"Ratu123!@#" --silent; do
          sleep 1
          echo "Waiting for MySQL..."
        done

    - name: Create Database if Not Exists
      run: |
        mysql -h 103.127.97.47 -u ratu -p"Ratu123!@#" -e "CREATE DATABASE IF NOT EXISTS ratu_report;"
        CREATE DATABASE IF NOT EXISTS ratu_report;
        GRANT ALL PRIVILEGES ON ratu_report.* TO 'ratu'@'%';
        GRANT ALL PRIVILEGES ON ratu_report.* TO 'ratu'@'localhost';
        FLUSH PRIVILEGES;

    - name: Run Migrations 
      env:
        DB_CONNECTION: mysql
        DB_HOST: 103.127.97.47
        DB_PORT: 3306
        DB_DATABASE: ratu_report
        DB_USERNAME: ratu
        DB_PASSWORD: Ratu123!@#
      run: php artisan migrate

    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/ratu_key
        chmod 600 ~/.ssh/ratu_key
        ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: ssh -i ~/.ssh/ratu_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} "echo SSH sukses!"

    - name: SSH and Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/InternshipLogistik
          if [ ! -f .env ]; then
            cp .env.example .env
            php artisan key:generate
          fi
          sudo git pull origin master
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          php artisan migrate --force
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan optimize
          sudo systemctl reload apache2
