name: CI/CD Laravel ke VPS

on:
  push:
    branches:
      - master
  
jobs:
  deploy-laravel-vps:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ratu_report
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_mysql, zip, bcmath
        coverage: none

    - name: Setup .env dari Secrets
      run: |
        echo "${{ secrets.ENV }}" | base64 --decode > .env
        cat .env | grep APP_KEY || echo "APP_KEY tidak ditemukan!"

    - name: Set Directory Permissions
      run: |
        sudo chmod -R 775 storage bootstrap/cache
        sudo chown -R www-data:www-data storage bootstrap/cache

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Wait for MySQL to be Ready
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -u root --password=root && break
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Run Migrations 
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ratu_report
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --force

    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/ratu_key
        chmod 600 ~/.ssh/ratu_key
        ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: ssh -i ~/.ssh/ratu_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} "echo SSH sukses!"

    - name: SSH dan Deploy ke VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/InternshipLogistik

          # Set .env dari GitHub Secrets
          echo "${{ secrets.ENV }}" | base64 --decode > .env

          # Set permission
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache

          # Pull kode terbaru
          sudo git pull origin master

          # Install dependencies
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev

          # Jalankan migrasi
          php artisan migrate --force

          # Clear cache
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan optimize

          # Restart Apache
          sudo systemctl reload apache2
