name: CI/CD

on:
  push:
    branches:
      - master
  
jobs:
  deploy-laravel-vps:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ratu_report
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_mysql, zip, bcmath
        coverage: none

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Set Directory Permissions (Pre-Key Generate)
      run: |
        sudo chmod 777 .env
        sudo chmod -R 775 storage bootstrap/cache
        sudo chown -R www-data:www-data storage bootstrap/cache

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Check .env Existence
      run: ls -lah .env && cat .env | grep APP_KEY || echo ".env is missing!"

    - name: Wait for MySQL to be Ready
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -u root --password=root && break
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Create Database if Not Exists
      run: |
        mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS ratu_report;"

    - name: Run Migrations And Seeders Database
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ratu_report
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate --seed

    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/ratu_key
        chmod 600 ~/.ssh/ratu_key
        ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: ssh -i ~/.ssh/ratu_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} "echo SSH sukses!"

    - name: SSH and Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /var/www/html/InternshipLogistik
          
          # Fix permissions before git pull
          sudo chown -R ${{ secrets.USERNAME }}:www-data .
          
          if [ ! -f .env ]; then
            cp .env.example .env
            php artisan key:generate
          fi
          
          # Pull latest changes
          sudo git pull origin master
          
          # Fix directory permissions
          sudo find . -type f -exec chmod 664 {} \;
          sudo find . -type d -exec chmod 775 {} \;
          
          # Set specific permissions for storage and bootstrap/cache
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache
          
          # Set vendor directory permissions
          sudo chown -R ${{ secrets.USERNAME }}:www-data vendor
          sudo chmod -R 775 vendor
          
          # Install dependencies with proper permissions
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          
          # Run Laravel commands
          php artisan migrate --seed --force
          php artisan config:clear
          php artisan cache:clear
          php artisan route:clear
          php artisan optimize:clear  # Clear all caches first
          php artisan optimize
          
          # Final permission adjustment
          sudo chown -R www-data:www-data storage bootstrap/cache
          sudo chmod -R 775 storage bootstrap/cache
          
          # Reload Apache
          sudo systemctl reload apache2
