name: CI/CD

on:
  push:
    branches: [ "master" ]
  
jobs:
  laravel-tests:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_DATABASE: ratu_report
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping --host=127.0.0.1 --user=root --password=root"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Setup PHP
      uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
        extensions: mbstring, pdo, pdo_mysql, zip, bcmath
        coverage: none

    - name: Copy .env
      run: cp .env.example .env

    - name: Install Dependencies
      run: composer install --no-interaction --prefer-dist --optimize-autoloader

    - name: Generate Application Key
      run: php artisan key:generate

    - name: Set Directory Permissions
      run: chmod -R 777 storage bootstrap/cache

    - name: Wait for MySQL to be Ready
      run: |
        for i in {1..30}; do
          mysqladmin ping -h 127.0.0.1 -u root --password=root && break
          echo "Waiting for MySQL..."
          sleep 2
        done

    - name: Create Database if Not Exists
      run: |
        mysql -h 127.0.0.1 -u root -proot -e "CREATE DATABASE IF NOT EXISTS ratu_report;"

    - name: Clear Config Cache
      run: php artisan config:clear

    - name: Run Migrations 
      env:
        DB_CONNECTION: mysql
        DB_HOST: 127.0.0.1
        DB_PORT: 3306
        DB_DATABASE: ratu_report
        DB_USERNAME: root
        DB_PASSWORD: root
      run: php artisan migrate 

    - name: Setup SSH Connection
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" | tr -d '\r' > ~/.ssh/ratu_key
        chmod 600 ~/.ssh/ratu_key
        ssh-keyscan -H ${{ secrets.IP }} >> ~/.ssh/known_hosts

    - name: Test SSH Connection
      run: ssh -i ~/.ssh/ratu_key -o StrictHostKeyChecking=no ${{ secrets.USERNAME }}@${{ secrets.IP }} "echo SSH sukses!"

    - name: SSH and deploy app
      uses: appleboy/ssh-action@master
      env:
          ENV: ${{ secrets.ENV }}
      with:
        host: ${{ secrets.IP }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        envs: ENV
        script: |
          cd /var/www/html/InternshipLogistik
          git pull origin master
          sudo chown -R www-data:www-data /var/www/html/InternshipLogistik
          sudo chmod -R 775 /var/www/html/InternshipLogistik/storage
          sudo chmod -R 775 /var/www/html/InternshipLogistik/bootstrap/cache
          composer install --no-interaction --prefer-dist --optimize-autoloader --no-dev
          php artisan migrate
          php artisan optimize
          sudo systemctl reload apache2
    
